### ISSUE TITLE
Is the NVM code tested and working?

### ISSUE THREAD

**Issue by BCITMike** [usb-c/STUSB4500#1]
I am trying to adapt our STM32 MCU code to read and write to the NVM registers so that the settings are saved persistently.

When I go to use nvm_flash(), the program hangs.  Given that your main doesn't use any of the NVM code, is it actually tested and working?  Generally, when I see this with other companies, it usually means code is incomplete and non functional.

Can you provide a simple example of it working from main?

Thanks

**Comment by usb-c** [comment]
Hi, The code to write the NVM has not been tested.
But the code executed in the main() has been tested and working.

**Comment by usb-c** [comment]
Tested the nvm_flash(), and it is working. 
The NVM memory is programmed as expected. No issue found.

**Comment by BCITMike** [comment]
Closing issue. My problem was I2C configuration related.
