### ISSUE TITLE
Incorrect definitions in USB_PD_defines.h

### ISSUE THREAD

**Issue by zambetti** [usb-c/STUSB4500#2]
There may be an error with some definitions in USB_PD_defines.h

The comment does not seem to match the values defined...

Line 25: /*"000" then No Operation
Line 26: "001" then Read 
...
Line 35: #define READ            0x00 //Read memory array

Elsewhere in the project: "READ" is used, resulting in an always-zero bitwise...

void CUST_ReadSector(uint8_t Port,char SectorNum, unsigned char *SectorData) { ...
Buffer[0]= (READ & FTP_CUST_OPCODE);

Is this intentional?

**Comment by usb-c** [comment]
yes the way it is written is intentional, because it is the generic way of writing bit-field values with masking.
FieldValue = Value & Mask

However, there is indeed an issue with the comments which doesn't match the values defined.
So the comments have been removed.
